export const API_KEY = '8FITdywSk07GYqpaNt1h7MJlSlHClXr7';
export const NEWS_CATEGORIES = [
    'arts', 'automobiles', 'books', 'business', 'fashion',
    'food', 'health', 'home', 'insider', 'magazine',
    'movies', 'national', 'nyregion', 'obituaries', 'opinion',
    'politics', 'realestate', 'science', 'sports', 'sundayreview',
    'technology', 'theater', 'tmagazine', 'travel', 'upshot', 'world'
];